const BASE_URL = 'http://localhost:8080'

export const USERREGISTER = `${BASE_URL}/register`;
export const GOOGLEREGISTER = `${BASE_URL}/register_google_auth`;
export const VERIFYOTP = `${BASE_URL}/verify_otp`;
export const RESENDOTP = `${BASE_URL}/resend_OTP`;
export const USERLOGIN = `${BASE_URL}/login`;
export const FORGOTPASSWORD = `${BASE_URL}/forgot_password`;
export const FORGOTPASSWORDOTP = `${BASE_URL}/forgot_password_otp`;
export const PASSWORDRESET = `${BASE_URL}/password_reset`;
export const GETUSERPROFILE = `${BASE_URL}/user_profile`;
export const GETCHILDTHERAPIST = `${BASE_URL}/childTherapy`;
export const GETSLOTS = `${BASE_URL}/slot_management`;
export const BOOKEDSLOTS = `${BASE_URL}/booked_slots`;
export const SAVEAPPOINTMENT = `${BASE_URL}/create_appointment`;
export const GETBOOKINGDETAILS = `${BASE_URL}/booking_status`;
export const GETSCHEDULEDBOOKINGS = `${BASE_URL}/booking_details`;
export const GETCOMPLETEDBOOKINGS = `${BASE_URL}/booking_Completeddetails`;
export const GETCANCELLEDBOOKINGS = `${BASE_URL}/booking_Cancelleddetails`;
export const SEARCHTHERAPIST = `${BASE_URL}/search_therapist`;
export const SORTCHILDTHERAPIST = `${BASE_URL}/sort_therapists`;